- i18n/de.yaml
- i18n/en.yaml
- layouts/partials/footer.html
**What this PR does / why we need it**: Copyright Date is not autogenerated this PR fixes it using the Hugo date format.
```release-note
```
> autogenerate year for copyright in footer

- exampleSite/content/about/hero.md
- exampleSite/content/index/hero.md
- layouts/partials/fragments/hero.html
No background added to hero fragment enable background on the jumbotron
fixes #37
> Set background on jumbotron hero fragment 

- package.json
There was no build command in package.json for building static files. This PR fixes that.
> Add webpack build command to package.json

- layouts/partials/fragments/hero.html
Don't include hero.js script when particls is disabled
fixes #172
> Don't include hero.js script when particls is disabled

- layouts/_default/single.html
- layouts/partials/fragments/buttons.html
- layouts/partials/fragments/contact.html
- layouts/partials/fragments/content-single.html
- layouts/partials/fragments/content-split.html
- layouts/partials/fragments/copyright.html
- layouts/partials/fragments/embed.html
- layouts/partials/fragments/footer.html
- layouts/partials/fragments/hero.html
- layouts/partials/fragments/item.html
- layouts/partials/fragments/items.html
- layouts/partials/fragments/logos.html
- layouts/partials/fragments/member.html
- layouts/partials/fragments/nav.html
- layouts/partials/fragments/table.html
Within each fragment .Name is now provided by single.html.
Single.html is centrally setting the name to simplified value.
The simplification removes any index.md files or paths,
which shouldn't be necessary within each fragment.
> Centralized fragment name generation

- layouts/partials/fragments/member.html
Member fragment had an extra color switch for part of it's text that was not needed since member fragment in single mode has a card which doesn't change color with background so the text was unreadable with some background colors.
fixes #215 
```release-note
Fix member fragment single member mode's text color in dark backgrounds
```
> Remove color switch for the title on member fragment in single mode

- exampleSite/config.toml
- exampleSite/content/blog/_index/index.md
- exampleSite/content/blog/archives/index.md
- exampleSite/content/blog/article-1/index.md
- i18n/en.yaml
- layouts/_default/single.html
- layouts/partials/fragments/list.html
- static/contact.js
- static/hero.js
- static/main.js
Add simple blog support. This PR adds support for index files to be fragments themselves to make smaller pages easier to create. Also adds list fragment that is able to list pages from different sections and is used in the exampleSite to list latest articles.
fixes #4 
```release-note
- Add new list fragment that lists pages from a single section
- Index files now can be fragments
```
> Add blog support

- theme.toml
Minimum required version has changed to v0.40
```release-note
Minimum required version of Hugo has changed to v0.40
```
> Bump minimum Hugo version required by Syna

- layouts/partials/fragments/items.html
The items fragment displayed items with icons. If there were no icons, the circle around it would still show. With this PR that is fixed.
fixes #197 
```release-note
Fix: Remove icon circle when there were no icons set in items fragment.
```
> Remove the icon container when there is no icon in items fragment

- exampleSite/content/about-split/content.md
- layouts/partials/fragments/content.html
Content fragment's sidebar can now be aligned on the right side of the page.
fixes #236 
```release-note
`content` fragment: Sidebar can be displayed on the right side.
```
> Make content sidebar alignment configurable

- exampleSite/content/_index/table.md
- layouts/partials/fragments/table.html
Table cells were not alignable. They were only capable of being centered and that did not work on header rows and button containing cells. This PR fixes these issues.
fixes #207 
```release-note
`table` fragment: You can now align table cells using `align` variable.
```
> Make table cell alignment more flexible and fix issues within it

- layouts/404.html
It migrates the current global directory to _global in 404 page.
fixes #228 
```release-note
Migrate 404 page from  global to _global
```
> Migrate 404 page from  global to _global

- exampleSite/content/_index/logos.md
- exampleSite/content/_index/logos_only.md
- exampleSite/content/dev/fallthrough/global/logos.md
- exampleSite/content/dev/fallthrough/page/logos.md
- layouts/404.html
- layouts/partials/fragments/logos.html
It changes all "name" instance to "text" to enable consistent naming for all fragments.
fixes #213 
```release-note
Fix naming consistency for logo fragment
```
> Fix naming consistency for logo fragment

- exampleSite/content/_index/item_image-table-left.md
- layouts/partials/fragments/item.html
- layouts/partials/fragments/table.html
Fix table and item fragment icon urls
fixes #209, #210
```release-note
bug: Item and table fragment icon urls were not working
```
> Fix table and item fragment icon urls

- layouts/404.html
Using alt text on the image seems like a good idea for this issue. It's more accessible as well.
fixes #248
> Fix 404 page logo alt text

- layouts/partials/fragments/item.html
Fix button alignment in item fragment when there is an icon
fixes #202 
Item fragment is too complicated. Let's consider simplifying it.
```release-note
bug: Item fragment didn't align buttons when there was an icon present
```
> Fix button alignment in item fragment when there is an icon

- exampleSite/content/_global/404.md
- layouts/404.html
- layouts/_default/single.html
- layouts/partials/fragments/404.html
- static/contact.js
- static/hero.js
- static/main.js
- static/portfolio.js
Make 404 page support fragments by creating a 404 fragment (same as the previous layout) and adding that fragment to the global fragments. 404 fragment will not be loaded anywhere except the 404 page if it's added in the global directory.
```release-note
404 page is now customizable using fragments
```
> Refactor 404 layout

- layouts/partials/fragments/member.html
- static-main/styles/_portfolio.scss
- static/syna-main.css
Fix issues with member and portfolio fragments when image is not provided. I don't like portfolio. The background solution is not pretty frankly. Let me know what you think.
Single member with image:
Single member with no image:
Member with image:
Member with no image:
Portfolio with image:
Portfolio with no image:
```release-note
- portfolio: Fix the size of the item with no image
- member: Remove image and realign data when no image is available for the item
```
> Fix issues with no image in portfolio and member fragments

- layouts/partials/fragments/list.html
Fix list fragment not showing the pages of a nested section
fixes #296 
```release-note
- list: Fix section variable default value for nested sections
```
> Fix default section in list fragment

- layouts/partials/fragments/portfolio.html
Display an error message in portfolio when no item is available
fixes #285 
```release-note
- portfolio: Display error message when no item is configured
```
> Display an error message in portfolio when no item is available

- exampleSite/content/_global/404.md
- layouts/partials/fragments/404.html
Add ability to add images for 404 and ability to resize them. The default image for 404 fragment is logo.svg.
fixes #278 
```release-note
- 404: Add ability to change and resize image
```
> Add ability to resize 404 image size

- exampleSite/content/dev/_index.md
- exampleSite/content/dev/_index/index.md
- exampleSite/content/dev/_index/list.md
- exampleSite/content/dev/empty-subitems/index.md
- exampleSite/content/dev/missing-images/index.md
- exampleSite/content/dev/resource-fallthrough/_index.md
- exampleSite/content/dev/resource-fallthrough/_index/index.md
- exampleSite/content/dev/resource-fallthrough/_index/list.md
- exampleSite/content/dev/resource-fallthrough/fragment/index.md
- exampleSite/content/dev/resource-fallthrough/global/index.md
- exampleSite/content/dev/resource-fallthrough/page/index.md
- exampleSite/content/dev/unconfigured-images/index.md
- exampleSite/content/fragments/_index/list.md
- layouts/partials/fragments/list.html
- layouts/partials/helpers/fragments.html
- List section had a check for the pages to see if the page's index file was a content fragment. This prevented listing pages with no content fragment or pages in which index was not a fragment or a different one.
- Added list page to the dev section
```release-note
list: Removed the check for the pages to ensure pages where content fragments
```
> Fix list fragment content check and add list page for dev section

- layouts/partials/fragments/items.html
- layouts/partials/fragments/member.html
- layouts/partials/fragments/portfolio.html
- layouts/partials/helpers/empty-subpath.html
- layouts/partials/helpers/warning.html
Extract warning message for not configured subitems
fixes #284 
```release-note
- New helper: **warning** - displays a simple alert
```
> Extract warning message for not configured subitems

- exampleSite/content/fragments/list/index.md
- layouts/partials/fragments/content.html
- layouts/partials/fragments/nav.html
- layouts/partials/helpers/categories.html
- layouts/partials/helpers/image.html
- layouts/partials/helpers/publish-date.html
- Fix margin between date, category and icon and text of github button in navbar
- Fix fallthrough issues
- Fix links in list example
fixes #350 
fixes #351 
fixes #352 
fixes #353
> Fix several regressions

- layouts/partials/fragments/buttons.html
- layouts/partials/fragments/contact.html
- layouts/partials/fragments/content.html
- layouts/partials/fragments/embed.html
- layouts/partials/fragments/header.html
- layouts/partials/fragments/items.html
- layouts/partials/fragments/list.html
- layouts/partials/fragments/member.html
- layouts/partials/fragments/portfolio.html
- layouts/partials/fragments/pricing.html
- layouts/partials/fragments/search.html
- layouts/partials/fragments/table.html
- layouts/partials/helpers/section-header.html
Extract title and subtitle from fragments into `section-header` helper, also adds title and subtitle to list fragment (was missing).
fixes #365
> Extract title and subtitle to a helper where possible

- exampleSite/content/dev/empty-subitems/pricing/index.md
- exampleSite/content/fragments/items/code-items-no-content.md
- exampleSite/content/fragments/items/code-items-only.md
- exampleSite/content/fragments/items/code-items.md
- exampleSite/content/fragments/items/code-logos-no-content.md
- exampleSite/content/fragments/items/code-logos-only.md
- exampleSite/content/fragments/items/code-logos.md
- exampleSite/content/fragments/member/code-members.md
- exampleSite/content/fragments/member/code-single-member.md
- exampleSite/content/fragments/portfolio/code-portfolio.md
- exampleSite/content/fragments/pricing/code-pricing.md
- layouts/partials/fragments/pricing.html
- layouts/partials/helpers/empty-subpath.html
Some fragments (portfolio, pricing, items, member) use subpath but had some issues. Examples lacked subpath items code examples, pricing fragment wasn't available in `/dev/empty-subitems` and didn't have a warning in case of no items.
**Which issue this PR fixes:**
fixes #362 
**Release note:**
```release-note
- pricing: Add warning message in case there are no items available
```
> Fix random issues with fragments using subpath

- layouts/partials/fragments/content.html
Add `.content` class to content container of content fragment, fixing max-width issue for images
fixes #376 
```release-note
- content: Fix max-width of images in the content
```
> Fix content fragment images max-width

- exampleSite/content/dev/blog/article-1/index.md
- layouts/partials/fragments/list.html
List fragment would render content fragment's `.Params.summary` if it's available instead of Hugo generated `.Summary`
fixes #321 
```release-note
- content: New frontmatter variable: summary: string, supports markdown
- list: Add ability to use content fragment's `.Params.summary` in case it's present and markdownify it.
```
> Add support for frontmatter summary in content fragment for list fragment

- layouts/partials/fragments/contact.html
Parly fixes netlify contact form submissions.
The netlify recaptcha configuration was a mixture of custom recaptcha and netlify injected recaptcha before. This is moved into the correct configuration for the netlify injected recaptcha.
Currently still a problem is that netlify seems to inject an additional recaptcha after submission aka it seems that it's ignoring the first recaptcha response, which is actually send in the correct POST request.
Also still annoying is the thank you notice being delivered out of page instead of inline.
```release-note
```
> Fix contact form

- exampleSite/content/docs/_index/content.md
- exampleSite/content/docs/development/content.md
Webpack's config file's link in the `/docs/development` page is fixed.
fixes #430
> Update webpack link in docs section

- exampleSite/content/fragments/config/config.md
- exampleSite/content/fragments/config/index.md
- layouts/partials/helpers/config.html
Config fragment now accepts resource instead of file which would accept both url and file.
> Update config fragment to accept resource instead of file

- layouts/partials/helpers/fragments-renderer.html
Add default value to fragments renderer loop
fixes #429
```release-note
- Fixed an issue where enabling taxonomy and taxonomyTerm kinds would break the build
```
> Add default value to fragments renderer loop

- layouts/partials/fragments/portfolio.html
- layouts/partials/fragments/pricing.html
Change column sizes in portfolio and pricing fragments
```release-note
- pricing, portfolio: Column sizes have changed in the tablet sizes to hold 1 column in each row (might be breaking)
```
> Change column sizes in portfolio and pricing fragments

- exampleSite/content/fragments/hero/code-hero.md
- exampleSite/content/fragments/hero/hero/config.json
- layouts/partials/fragments/hero.html
- Revert particles config to default
- Add particles config to example code
- Fix `width` and `height` not taking effect
fixes #520 
```release-note
- hero: Fix logo not being displayed in the given `height` and `width`
```
> Patched some issues within the hero fragment

- exampleSite/content/fragments/member/code-single-member.md
- exampleSite/content/fragments/member/members/ella.md
- exampleSite/content/fragments/member/members/gopher.md
- exampleSite/content/fragments/member/members/hector.md
- exampleSite/content/fragments/member/members/nancy.md
- exampleSite/content/fragments/member/members/yoda.md
- exampleSite/content/fragments/member/single-member/bio.md
- i18n/en.yaml
- layouts/partials/fragments/footer.html
- layouts/partials/fragments/hero.html
- layouts/partials/fragments/item.html
- layouts/partials/fragments/items.html
- layouts/partials/fragments/member.html
- layouts/partials/fragments/nav.html
- layouts/partials/fragments/search.html
- layouts/partials/fragments/toc.html
Adds alt and title tags along with `.sr-only` elements to icons and images
fixes #400 
```release-note
- Accessibility: Icons and images now have proper alt and title tags
```
> Add alt and title tags along with sr-only to images and icons

- exampleSite/content/docs/deployment/content.md
- exampleSite/content/fragments/404/docs.md
- exampleSite/content/fragments/_global/config.md
- exampleSite/content/fragments/buttons/docs.md
- exampleSite/content/fragments/config/docs.md
- exampleSite/content/fragments/config/index.md
- exampleSite/content/fragments/contact/docs.md
- exampleSite/content/fragments/content/docs.md
- exampleSite/content/fragments/copyright/docs.md
- exampleSite/content/fragments/embed/docs.md
- exampleSite/content/fragments/faq/docs.md
- exampleSite/content/fragments/footer/docs.md
- exampleSite/content/fragments/graph/docs.md
- exampleSite/content/fragments/header/docs.md
- exampleSite/content/fragments/hero/docs.md
- exampleSite/content/fragments/item/docs.md
- exampleSite/content/fragments/items/docs.md
- exampleSite/content/fragments/list/docs.md
- exampleSite/content/fragments/member/docs.md
- exampleSite/content/fragments/nav/docs.md
- exampleSite/content/fragments/portfolio/docs.md
- exampleSite/content/fragments/pricing/docs.md
- exampleSite/content/fragments/react-portal/docs.md
- exampleSite/content/fragments/search/docs.md
- exampleSite/content/fragments/stripe/docs.md
- exampleSite/content/fragments/table/docs.md
- exampleSite/content/fragments/toc/docs.md
- layouts/partials/helpers/config.html
- Add documentation for:
- item
- items
- config
- DEMO_MODE
- .Site.Params.debug
- Add link to asset documentation
- Change background color of code sections using a global config fragment
fixes #480 
fixes #552 
I also applied a small change to config fragment that doesn't have any impacts. If you want I can move it to a patch PR.
> Update documentation 

- layouts/_default/list.html
- layouts/partials/fragments/editor.html
- layouts/partials/fragments/graph.html
- layouts/partials/fragments/hero.html
- layouts/partials/head.html
- layouts/partials/helpers/config.html
- layouts/partials/helpers/fragments.html
- layouts/partials/helpers/image.html
- layouts/partials/js.html
- Remove `uniq` function where it was comparing an array containing different values
- Fix `.Dir` depreciation warning
- Fix `.Hugo` depreciation warning
fixes #562 
There is another deprecation warning that is not affecting the build. It's related to `Page.URL` variable. Fixing it is a bit problematic since for example contact fragment:139:76 would function differently if we change it. I think we should discuss that fix in another issue.
> Upgrade to hugo v0.55.5

- exampleSite/content/dev/_index/list.md
- exampleSite/content/fragments/list/docs.md
- exampleSite/content/fragments/list/list.md
- layouts/partials/fragments/list.html
Add support for two new variables in the list fragment: `sort`, `sort_order`. These two variables change the sort variable and order for the list fragment. It wasn't possible to use `ByTitle` or other variables that Hugo exposes on the page collection since we collect pages and combine them with sections.
fixes #583 
```release-note
List: Add `sort` and `sort_order` variables
```
> Add support for sort order in the list fragment

- layouts/partials/helpers/fragments.html
Fix 404 page not displaying it's fragments. It was a null check.
fixes #575
```release-note
- 404 page: Fragments were not being shown due to a change in Go template conditionals
```
> Fix fragments not showing in the 404 page

- layouts/partials/fragments/faq.html
- layouts/partials/fragments/items.html
- layouts/partials/fragments/member.html
- layouts/partials/fragments/portfolio.html
- layouts/partials/fragments/pricing.html
- layouts/partials/helpers/fragments.html
- layouts/partials/helpers/image.html
- layouts/partials/helpers/subitems.html
Global fragments with subitems (member, items, portfolio, faq) now display their subitems instead of "empty subitems" warning.
fixes #582 
```release-note
- Fixed global fragments with subitems showing warning instead of items
```
> Fix global fragments with subitems showing warning

- layouts/partials/fragments/hero.html
The hero fragment allows a user to include an asset in the hero banner. However, the HTML for the img tag is broken if width and/or height is set:
<img
class="overlay img-fluid"
src="/images/logo.svg"
alt="logo"width="500px"></img>
Notice missing space before width. This PR fixes this.
```
Hero fragment: Added missing space before height/width attributes in <img> tag
```
> Fix missing space before height and width attributes in asset img tag

- layouts/partials/fragments/content.html
- layouts/partials/helpers/container.html
fixes #621 
```release-note
- content: Content fragment now supports `padding` variable like other fragments, making use of our container helper
```
> Add container to content fragment

- layouts/partials/fragments/list.html
- layouts/partials/helpers/list-pages.html
Extracts the new list-pages helper from the list fragment.
fixes #623 
```release-note
- list-pages: A new list-pages helper is available to help create list fragments.
```
> Extract list-pages helper from list fragment

- layouts/_default/baseof.html
Webpages made with Syna don't pass W3C validator, a DOCTYPE is expected at the beginning of the web.
This fix adds the expected html5 declaration so web browsers can work in standards mode.
Most other themes use this declaration.
https://validator.w3.org/nu/?doc=https%3A%2F%2Fabout.okkur.org%2F
https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
```release-note
Fix: (W3C) Start tag seen without seeing a doctype first
```
> add doctype to fix w3c error:

- layouts/partials/head.html
`http-equiv=content-language` is obsolete and deprecated, Syna is already using the new preferred method `<html lang="XX">`
[W3 Test validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fabout.okkur.org%2Fsyna)
https://www.w3.org/TR/2011/WD-html-markup-20110113/meta.http-equiv.content-language.html
https://www.w3.org/International/questions/qa-http-and-lang
```release-note
Improve W3C conformance removing http-equiv="Content-Language"
```
> Using the meta element to specify the default language is obsolete

- layouts/partials/head.html
The `value` attribute should be changed to `content="notranslate"` in order to pass HTML5 validation.
https://support.google.com/webmasters/answer/79812?hl=en
https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome
```release-note
Improve HTML5 conformance 
```
> Meta google

- layouts/_default/baseof.html
One less w3 validator's error without the stray div.
I don't know exactly what this block of code does, but anyway better to have it clean and tidy.
There is another error with `<img src="" alt="" class="img-fluid">` been empty, but I'm not sure if is there for a especial use case.
```release-note
Minor fix: remove "tray end tag div" error
```
> Remove stray end tag div and indent block

- layouts/partials/fragments/content.html
- layouts/partials/fragments/copyright.html
- layouts/partials/fragments/hero.html
- layouts/partials/fragments/nav.html
- layouts/partials/helpers/categories.html
- layouts/partials/helpers/publish-date.html
- layouts/partials/helpers/section-header.html
Add classes to some of the fragments' elements
fixes #626 
```release-note
- styling: content, nav, hero, copyright and all fragments' title and subtitle now offer classes for styling
```
> Add classes to some of the fragments elements

- layouts/partials/helpers/container.html
Container helper was showing go string with nil replacement errors in all the fragments so I added default classes where it needed so the weird strings will disappear.
> Add default section and container class to container helper

- layouts/partials/helpers/list-pages.html
Fix sort order of list fragment.
fixes #663 
```release-note
- list: Change sort order from ascending to descending.
```
> Fix sort order of list fragment

- layouts/partials/fragments/list.html
- layouts/partials/head.html
- layouts/partials/helpers/page-title.html
Add default page title using title of the first content fragment found in
page.
fixes (partially) #655 
This PR only adds default title to the page. Removing date metadata which was mentioned in the issue is not done and I don't think fixing it in the same PR is a good idea since the change is a bit complicated already.
```release-note
- page: Each page now uses the first content fragment's title as page title by default.
```
> Add default page title

- exampleSite/config-dev.toml
- exampleSite/config.toml
`languageLang` in `exampleSite/config[-dev].toml` seems an obsolete option.
I've searched in the [Hugo Docs](https://gohugo.io/getting-started/configuration/#all-configuration-settings) and in the [github's repos](https://github.com/gohugoio) but I dont' find `languageLang` anywhere.
`defaultContentLanguage` is documented and is propably the correct option.
```release-note
Change languageLang to defaultContentLanguage in config.toml
```
> languageLang is not in the Hugo documentation, defaultContentLanguage is

- layouts/partials/helpers/list-pages.html
List fragment didn't list pages from some sections.
fixes #650 
```release-note
- list: Fix list fragment not working on some sections
```
> Fix list fragment not listing pages from all sections

- exampleSite/content/docs/deployment/index.md
- exampleSite/content/docs/multilingual/content.md
- exampleSite/content/docs/multilingual/index.md
- layouts/partials/helpers/fragments.html
- layouts/partials/helpers/image.html
Adds basic support for multilingual websites.
I'll add documentation and examples ASAP.
fixes #14
fixes #680 
```release-note
- Syna now supports multilingual websites out of the box
```
> Add basic support for multilingual

- layouts/partials/fragments/hero.html
Previously syna api would have kept a reference to particles
canvas even when particles was disabled on the hero element.
This commit fixes that issue and removes useless code.
fixes #703 
```release-note
- hero: Remove extra code when particles is disabled
```
> Remove particle selector registration when disabled

- layouts/partials/head.html
Previously we had hardcorded opengraph meta tags in our
head partial but with the internal opengraph template in
Hugo there's no need for that anymore.
fixes #642 
```release-note
- Make use of [opengraph internal template](https://gohugo.io/templates/internal/#open-graph)
```
> Make use of Hugo internal opengraph template

- .github/workflows/cypress.yml
This was causing our tests failing
https://github.com/cypress-io/github-action#important
> Switch to ubuntu-1604 instead of ubuntu-latest for github action

- layouts/partials/head.html
- layouts/partials/js.html
A few static resources are currently generated with a language tag, which prevents them from loading since hugo does not generate localized static assets (afaik).
Only tested on my machine, seemed to work there. There is another usage in [this](https://github.com/okkur/syna/blob/master/layouts/partials/helpers/config.html) file, but I was not sure how it is used and therefore did not touch it.
```release-note
Fix bug that created localized urls for static assets.
```
> Remove relLangURL from script and favicon links

- layouts/partials/helpers/publish-date.html
Fixes date format config not being used. $.Site wasn't the correct entrypoint, but should have been .root.Site due to it being injected into the partial from us.
fixes #736
```release-note
Fix global date_format config not being applied
```
> Fix date_format config

- cypress/integration/events.spec.js
`relLangURL` had caused the urls in pricing fragment to change from absolute to relative, which in turn invalidated the selectors in our tests. Changing from exact match (`[href=/path]`) to regex match (`[href$=/href]`) fixed the problem.
fixes #748
> Fix events tests' bad selector error

- layouts/partials/helpers/list-pages.html
`.Pages` previously only returned pages with `.Kind eq "page"` but now it returns all pages under a section. Changed our list helper to collect pages based on their `.Kind` if `subsections` is not set or is set to false.
fixes #751
```release-note
- list: Fix a bug that caused subsections be shown if the config was set to not show them or show duplicate subsections if config was set to show them.
```
> Fix duplicate section pages in list fragment

- exampleSite/content/fragments/contact/contact.md
- exampleSite/content/fragments/contact/docs.md
- i18n/en.yaml
- layouts/partials/fragments/contact.html
This is an idea I've been thinking about for a while and when I saw the issue, thought I create a PR for it. It's a breaking change since the config will change, but I added default inputs same as our previous sample. Please let me know what you think.
fixes #753 
This is a work in progress and an idea. Please do not merge.
```release-note
- **UPDATE IF PR IS APPROVED**
```
> WIP: Allow custom inputs (idea)

- layouts/partials/helpers/fragments.html
Config fragment output was duplicated since in the fragments helper, we didn't remove the duplicated ones where we were adding the fragments to the page config.
fixes #760
```release-note
- config: Fixed duplicated output
```
> Remove duplicated config fragments

- layouts/partials/fragments/hero.html
Fix image height not working on hero.asset.
fixes #734 
```release-note
- hero: image.height works without an issue now
```
> Fix hero image params' height issue

- assets/js/contact.js
Fix alignment of contact fragment submit button when recaptcha is not fully loaded
fixes #722
I'm not sure if this will fix the issue or not. I can't test it locally but in theory it should work. I tried to check whether or not the recaptcha badge is loaded into the dom. Since flex will break when we hide the filler right after if see the recaptcha, checking a deeper element should fix the issue.
```release-note
- contact: fix alignment of contact fragment's submit button when recaptcha is not fully loaded
```
> Fix alignment of contact fragment submit button

- cypress/integration/list.spec.js
Previous test was wrong since I hadn't realized list fragment was outputing extra content. Since the fragment was fixed and the test was hard coded, it was failing.
> Fix list item count in the list test

- layouts/partials/helpers/fragments-renderer.html
Updates to hugo 0.71.1 causes a previously allowed-but-wrong construct to now be disallowed.  This fixes the template to now compile on 0.71.1
Fixes okkur/syna#773
Fixes an template that is now illegal in hugo 0.71.1
Also discussed in gohugoio/hugo#7325
```release-note
Fixes template error in hugo 0.71.1
```
> Fix broken if and statement

- layouts/partials/fragments/list.html
Add a bit of whitespace around title of list fragment articles. The effect is visible only in list mode and not tiled mode which is unaffected.
fixes #653 
This can be considered something of a change proposal in accordance to the issue. If the current design doesn't look very good or needs further change, I recommend more discussion and we can update this PR accordingly. Creating several PRs for design updates would be a bit confusing and hard to fix merge conflicts if they arise.
```release-note
list: Update whitespace in list mode
```
> Add more whitespace to list fragment

- cypress/integration/navbar.spec.js
- exampleSite/content/dev/nav-multiple/index.md
- exampleSite/content/dev/nav-multiple/nav-1.md
- exampleSite/content/dev/nav-multiple/nav-2.md
- layouts/partials/fragments/nav.html
Fixed the search script in the nav fragment, allowing multiple nav fragments to use search in the same page.
fixes #388 
The sticky option can be used but we may need to rethink how it might function differently for multiple nav fragments. Right now if you have two sticky navs, they are followed by each other on top of the page. If we need a different behavior, I suggest doing so in a separate issue.
```release-note
- nav: Fix the bug that prevented search from working if there were multiple nav fragments in one page
```
> Fix nav fragment to allow multiple navs per page

- layouts/partials/helpers/subitems.html
`subitems` helper didn't identify page resources correctly in multilingual websites. The problem appeared in not default language pages.
fixes #799 
```release-note
- Fix multilingual pages not showing subitems of fragments in non default language page
```
> Update subitems helper to fix multilingual issue

- cypress/integration/main-js.spec.js
- layouts/partials/fragments/buttons.html
- layouts/partials/fragments/contact.html
- layouts/partials/fragments/content.html
- layouts/partials/fragments/editor.html
- layouts/partials/fragments/embed.html
- layouts/partials/fragments/faq.html
- layouts/partials/fragments/footer.html
- layouts/partials/fragments/graph.html
- layouts/partials/fragments/header.html
- layouts/partials/fragments/item.html
- layouts/partials/fragments/items.html
- layouts/partials/fragments/list.html
- layouts/partials/fragments/member.html
- layouts/partials/fragments/portfolio.html
- layouts/partials/fragments/pricing.html
- layouts/partials/fragments/react-portal.html
- layouts/partials/fragments/search.html
- layouts/partials/fragments/stripe.html
- layouts/partials/fragments/table.html
- layouts/partials/helpers/container.html
- layouts/partials/helpers/fragments-renderer.html
- layouts/partials/helpers/subitems.html
Fragment names didn't omit language name which was causing JS selectors to fail. This PR renames `<fragment>.<lang>` to `<fragment>`.
fixes #798 
fixes #799 
```release-note
- Fix scripts not working in multilingual websites properly
```
> Fix rel lang fragment name issue

- exampleSite/content/fragments/repositories_github/code-repositories_github.md
- exampleSite/content/fragments/repositories_github/docs.md
- exampleSite/content/fragments/repositories_github/repositories_github.md
- layouts/partials/fragments/repositories_github.html
Add a new variable `allowlist` to `repositories_github` fragment, filtering repositories by name.
fixes #805 
```release-note
- repositories_github: Add new `allowlist` variable
```
> Add allowlist to repositories_github

- exampleSite/content/dev/fragment-fallthrough/_global/config.md
- exampleSite/content/dev/fragment-fallthrough/_global/hidden.md
- exampleSite/content/dev/fragment-fallthrough/_index/config.md
- exampleSite/content/dev/fragment-fallthrough/_index/content.md
- exampleSite/content/dev/fragment-fallthrough/_index/hidden.md
- exampleSite/content/docs/fragments/content.md
- exampleSite/content/docs/global-variables/content.md
- layouts/partials/helpers/fragments-renderer.html
- layouts/partials/helpers/fragments.html
Add new global variable `hide` and tests in the fragment fallthrough dev page for it
fixes #731 
```release-note
- added new global variable `hide` in order to bypass global fragments
```
> Add new global variable hide

- exampleSite/config.toml
Frontmatter's config was not indented properly. Not sure if it was breaking something, hadn't noticed any issues and the problem seem to be quite old at this point.
> Fix indenetation of frontmatter's config

- exampleSite/content/fragments/faq/code-faq.md
- exampleSite/content/fragments/graph/code-stats.md
- exampleSite/content/fragments/items/code-items-no-content.md
- exampleSite/content/fragments/items/code-items-only.md
- exampleSite/content/fragments/items/code-items.md
- exampleSite/content/fragments/items/code-logos-no-content.md
- exampleSite/content/fragments/items/code-logos-only.md
- exampleSite/content/fragments/items/code-logos.md
- exampleSite/content/fragments/member/code-members.md
- exampleSite/content/fragments/member/code-single-member.md
- exampleSite/content/fragments/portfolio/code-portfolio.md
- exampleSite/content/fragments/pricing/code-pricing.md
- layouts/partials/helpers/subitems.html
This allows to disable subitems for example in the portfolio by setting `disabled = true` just like on other pages.
None.
```release-note
Honor "disabled" on subitems.
```
> Honor "disabled" on subitems.

- layouts/partials/head.html
Disable postcss asset pipes by default, it requires `postcss` variable to be set to `true` in site's `Params` config.
fixes #813 
```release-note
- Fix issue preventing site build when `postcss-cli` is not installed
```
> Fix postcss issues

- layouts/partials/fragments/contact.html
When a user doesn't write a message on the contact page, the wrong error is displayed: 'Send Message' instead of 'Please enter a message'.
> Display correct error on contact page

- i18n/en.yaml
Doing a 'grep -R i18n layouts' revealed some unlisted elements.
> Add missing translation strings

- assets/styles/_pricing.scss
- exampleSite/content/fragments/pricing/pricing/plan-1.md
Adding  the ability to make  the pricing icons red.
This one was achieved by adding a new style to `_pricing.css` called `red`.  I added an example about how to use it inside the exampleSite's `plan-1.md`. I'm not sure if it is the preferred way to achieve this effect but I'm pretty sure it is the less disruptive one.
```release-note
- Adding the ability to use red icons inside the pricing features;
```
> Adding pricing red icons css with example.

- layouts/partials/helpers/fragments.html
This PR replaces the use of the `ne` template function with only one argument with an equivalent `not`. Hugo enforces this as of v0.92.2, which currently breaks the build of a Syna-based site on the latest versions.
fixes #868 
All the other uses of `ne` comparisons I could find, did correctly use 2 arguments.
```release-note
Restore compatibility with Hugo v0.92.2
```
> Restore compatibility with Hugo v0.92.2

- layouts/partials/fragments/footer.html
Is this a BUG REPORT or FEATURE REQUEST?:
bug
What happened:
On deployment to S3, social media links in the Footer fragment are broken. Instead of linking to the social media page, they create a relative link with the website URL first, followed by the social media page.
What you expected to happen:
Social media links correctly link to the appropriate page
How to reproduce it (as minimally and precisely as possible):
Deploy a website and follow a social media link from the footer fragment (does not occur in local 'hugo server' site)
-->
```release-note
```
> Fix footer for footer_social

- layouts/partials/fragments/list.html
in the helper the variable is called `renderPagination` not `render_pagination`
fixes #887
> fix pagination

- layouts/partials/js.html
Update the internal template reference
As other themes did https://github.com/google/docsy/pull/1931
PD Last hugo version working for me is 0.122.0
```release-note
Fix _internal/google_analytics_async deprecation warning
```
> Fix _internal/google_analytics_async deprecation warning

- exampleSite/config-dev.toml
- exampleSite/config.toml
Deletes the deprecated term in the exampleSite
```release-note
Fix deprecated taxonomyTerm in exampleSite
```
> Fix deprecated taxonomyTerm
