netlify.toml
=> Workaround theme directory

layouts/_default/baseof.html, layouts/_default/single.html, layouts/_default/split.html
Adds `baseof.html` layout so some more used partials can settle in there.
fixes #29
I'm not sure if this is the implementation #29 needs. Let me know if this is not the change you're looking for.
```release-note
```
=> Add baseof template

layouts/partials/nav.html, static/css/syna.css, static/js/syna.js
Adds scroll to top.
fixes #34
```release-note
```
=> Add scroll to top button

exampleSite/config.toml, layouts/partials/footer.html
(#39)
Attribution still displays even with false assigned to it. Fix for this is to completely remove it from config.toml
```release-note
```
=> Remove attribution from footer

exampleSite/config.toml
Add attribution opt-in / opt-out option
**Special notes for your reviewer**: 
This is what it should look like right?
```
```
=> Add opt-in option for footer attribution

exampleSite/config.toml, static/css/syna.css
Rounded corners are visible with a different background color 
fixes #40 
```release-note
```
=> Fix rounded corners in hero jumbotron visible 

exampleSite/content/index/contact.md, layouts/partials/fragments/contact.html
Adds support for netlify form-handling
fixes #43 
This might not be a good solution since it doesn't take any global configuration into account
```release-note
```
=> Add support for netlify form-handling

exampleSite/config.toml, layouts/_default/baseof.html
FYI, I hate Hugo!
This enables the user to display/hide navigation with an option when there are no menus.
fixes #36
```release-note
```
=> Add ability to display navbar with no menus available

layouts/partials/_analytics/piwik.html, layouts/partials/fragments/hero.html
Check for all possible occurrences of paragraph tag using markdown content and change to div tag.
fixes #31 
Already fixed in #25 but this is an overall check.
=> Move markdown content from <p> to <div>

exampleSite/content/index/sample-custom-fragment.md, exampleSite/layouts/partials/fragments/sample-custom-fragment.html, layouts/_default/single.html
Adds support for custom fragments
fixes #12 
This is just to test the functionality. If everything is fine let me know and we can add the feature to all of our default pages.
```release-note
```
=> Add custom fragment support

static/css/syna.css
**What this PR does / why we need it**: Enable full width for particle.js in hero fragment. 
fixes #78
=> Fix full width coverage for particle.js

exampleSite/config.toml, layouts/partials/fragments/footer.html
Changes footer social menus to snake case
fixes #91 
Did not change legalFooter since that is addressed in #97
=> Refactor menu names to snake_case

layouts/partials/nav.html
Fixes GitHub icon in star button
fixes #99
=> Fix github icon #99

exampleSite/content/about/footer.md, exampleSite/content/index/footer.md, layouts/partials/fragments/footer.html
Add link support to logo in the footer fragment
fixes #106
=> Add support for linking logo in footer fragment

layouts/partials/nav.html, static-main/styles/syna.scss, static/main.css
Remove hardcoded background color in syna.css and set it use primary color from variables assigned.
**Which issue this PR fixes** *(optional - uncomment and add issue)*: 
fixes #112
=> Fix scroll-to-top bgcolor

exampleSite/config.toml, exampleSite/content/global/nav.md, layouts/404.html, layouts/_default/baseof.html, layouts/partials/fragments/nav.html
Makes navbar a fragment instead of a hardcoded partial.
fixes #89 
This is based on #118 so please wait for that to be merged.
```release-note
Navbar is now a fragment
```
=> Make navbar a fragment

exampleSite/layouts/partials/fragments/sample-custom-fragment.html, layouts/_default/baseof.html, layouts/_default/single.html, layouts/partials/custom/css.html, layouts/partials/custom/js.html, layouts/partials/fragments/buttons.html, layouts/partials/fragments/contact.html, layouts/partials/fragments/content-single.html, layouts/partials/fragments/content-split.html, layouts/partials/fragments/copyright.html, layouts/partials/fragments/embed.html, layouts/partials/fragments/footer.html, layouts/partials/fragments/hero.html, layouts/partials/fragments/item.html, layouts/partials/fragments/items.html, layouts/partials/fragments/logos.html, layouts/partials/fragments/member.html, layouts/partials/fragments/nav.html, layouts/partials/fragments/table.html, layouts/partials/head.html, layouts/partials/js.html
Remove extra new lines in layout files (layouts, partials and fragments)
fixes #60 
I removed as much as was possible and in some places I couldn't figure out how to avoid smelly HTML output. If there is anything too serious let me know. (Also God bless VIM macros)
=> Remove extra whitespace in layout files

Makefile, Procfile, package.json, yarn.lock
Add makefile to build and run a development server
fixes #127 
```release-note
```
=> Add makefile

exampleSite/config.toml
Remove unused contact.disable config from exampleSite config
fixes #146
=> Remove unused contact.disable config from exampleSite config

exampleSite/content/index/portfolio.md, exampleSite/content/index/portfolio/bio.md, layouts/partials/fragments/member.html
**What this PR does / why we need it**: Showcase a single member on its own fragment.
fixes #27 
**Special notes for your reviewer**: I added bootstrap card style for the display i'd like to get your opinion about it.
=> Add Single Member Fragment

exampleSite/config.toml, exampleSite/content/about-split/content-split.md, exampleSite/content/about/content.md, exampleSite/content/about/footer.md, exampleSite/content/global/footer.md, exampleSite/content/index/awesome-team/donald.md, exampleSite/content/index/awesome-team/ella.md, exampleSite/content/index/awesome-team/gopher.md, exampleSite/content/index/awesome-team/hector.md, exampleSite/content/index/awesome-team/nancy.md, exampleSite/content/index/awesome-team/yoda.md, exampleSite/content/index/items/column1.md, exampleSite/content/index/items/column2.md, exampleSite/content/index/items/column3.md, exampleSite/content/index/items_only/column-1.md, exampleSite/content/index/items_only/column-2.md, exampleSite/content/index/items_only/column-3.md
Cleanup of various content files.
=> Cleanup files

exampleSite/content/index/awesome-team/donald.md, exampleSite/content/index/awesome-team/ella.md, exampleSite/content/index/awesome-team/gopher.md, exampleSite/content/index/awesome-team/hector.md, exampleSite/content/index/awesome-team/nancy.md, exampleSite/content/index/awesome-team/yoda.md, exampleSite/content/index/portfolio/bio.md
Change `joined` to `date` within the member content files for consistency.
fixes #164
=> Modify joined to date within member frontmatter

exampleSite/content/index/items/column1.md, exampleSite/content/index/items/column2.md, exampleSite/content/index/items/column3.md, exampleSite/content/index/items_only/column-1.md, exampleSite/content/index/items_only/column-2.md, exampleSite/content/index/items_only/column-3.md, layouts/partials/fragments/item.html, layouts/partials/fragments/items.html
Change name to title within the item fragment
fixes #163
=> Rename item fragment name to title

layouts/_default/single.html, layouts/partials/fragments/buttons.html, layouts/partials/fragments/contact.html, layouts/partials/fragments/content-single.html, layouts/partials/fragments/content-split.html, layouts/partials/fragments/copyright.html, layouts/partials/fragments/embed.html, layouts/partials/fragments/footer.html, layouts/partials/fragments/hero.html, layouts/partials/fragments/item.html, layouts/partials/fragments/items.html, layouts/partials/fragments/logos.html, layouts/partials/fragments/member.html, layouts/partials/fragments/nav.html, layouts/partials/fragments/table.html
Simplify call to .Params and make all fragment code more consistent.
=> Simplify fragments by using .Params without assignment

layouts/partials/fragments/contact.html
Fixes the default hidden contact fields.
=> Fix hidden contact fields

docs/README.md
Document Syna supported colors and how to use and customize them.
fixes #16 
```release-note
Document supported colors 
```
=> Add supported colors documentation

exampleSite/content/dev/empty/index.md, exampleSite/content/dev/empty/items.md, exampleSite/content/dev/empty/member.md, layouts/partials/fragments/items.html, layouts/partials/fragments/member.html
Add an alert prompt to fragment with content data not available. 
Optional one line note for this specific change, that can be used in a release-note or changelog.
```release-note
Add an alert prompt to fragment with content data not available. 
```
=> Enable alert prompt for fragment with content not available

CHANGELOG.md
Update the changelog with my changes and fix a few typos
=> Update the changelog with mpourismaiel changes

CHANGELOG.md
=> Add more entries in CHANGELOG

README.md
Add attribtuion to Syna 
fixes #193 
```release-note
Add attribution to README.md
```
=> Add author attribution

exampleSite/config.toml
**What this PR does / why we need it**:                                                                                                                                                                                                                    
Add site version to config
```release-note
Add site version to config.toml file
```
=> Add syna version to config.toml

layouts/partials/fragments/member.html
Production ready use for single member mode.
https://deploy-preview-204--syna-demo.netlify.com/#single-member-fragment
```release-note
Improve structure and design of single member mode for member fragment
```
=> Restructure single member mode

exampleSite/content/_index/portfolio/bio.md
It adds company example to single-member mode fragment
fixes #211
```release-note
Add company example to single member mode fragment
```
=> Add company key to single member mode fragment

docs/fragments/README.md, docs/fragments/contact.md
Add new documentation page for fragments and documented contact fragment.
fixes #199 
```release-note
Updated documentation
```
=> Add documentation for the contact form fragment

exampleSite/content/_index/contact.md, layouts/partials/fragments/contact.html
It fixes the naming convention used within contact fragment
```release-note
Make naming consistent within contact fragment
```
=> Make naming consistent within contact fragment

docs/README.md
Adds documentation that explains how to use custom favicons.
fixes #196
=> Add documentation for favicon customization

layouts/partials/fragments/copyright.html
Change the url for theme attribution
fixes #208
=> Change the url for theme attribution

layouts/partials/fragments/contact.html
It adds support for netlify custom recaptcha
```release-note
Add support for netlify custom recaptcha
```
=> Add support for netlify custom recaptcha

exampleSite/content/dev/empty-subitems/index.md, exampleSite/content/dev/empty-subitems/items/index.md, exampleSite/content/dev/empty-subitems/member/index.md, exampleSite/content/dev/empty-subitems/portfolio/index.md, exampleSite/content/dev/empty/index.md
=> Rework empty subitem dev demo

exampleSite/content/_index/header.md, exampleSite/content/_index/section-header.md, layouts/partials/fragments/header.html
Header fragment now supports alignment
fixes #283 
```release-note
- header: Added support for alignment of title and subtitle
```
=> Add alignment variables for header fragment

layouts/partials/custom/css.html, layouts/partials/custom/js.html, layouts/partials/fragments/contact.html, layouts/partials/fragments/editor.html, layouts/partials/fragments/hero.html, layouts/partials/fragments/list.html, layouts/partials/fragments/portfolio.html, layouts/partials/fragments/react-portal.html, layouts/partials/head.html, layouts/partials/helpers/image.html, layouts/partials/js.html
Change all relative url pipes to relLangURL. This is done automatically so some stuff might be missing but I checked around seems everything is covered
fixes #276
=> Change all relative url pipes to relLangURL

layouts/partials/fragments/item.html, layouts/partials/fragments/table.html, layouts/partials/helpers/table.html
Extract table into a helper from table and item fragment
fixes #280 
```release-note
- table, item: Extract table into it's helper
```
=> Extract table into a helper from table and item fragment

layouts/partials/fragments/content.html, static-main/styles/_syna.scss, static/syna-main.css
Fix image max width issue in content fragment
fixes #329
```release-note
- content: Fix image max width issue
```
=> Fix image width in content fragment

exampleSite/content/fragments/list/code-list-tiled.md, exampleSite/content/fragments/list/code-list.md, exampleSite/content/fragments/list/index.md, exampleSite/content/fragments/list/list-tiled.md, exampleSite/content/fragments/list/list.md
Create list fragment example
fixes #312
=> Create list fragment example

exampleSite/content/fragments/list/code-list-tiled.md, exampleSite/content/fragments/list/code-list.md, exampleSite/content/fragments/list/list-tiled.md, exampleSite/content/fragments/list/list.md, exampleSite/content/fragments/search/search.md, layouts/partials/fragments/nav.html, layouts/partials/fragments/search.html, layouts/partials/helpers/search-result-template.html, static-main/styles/_search.scss, static/syna-main.css
Fix background and text color of search in search and nav fragments
fixes #338
=> Fix background and text color of search in search and nav fragments

CHANGELOG.md
Update Changelog including all changes for v0.13.0 release.
=> Update CHANGELOG for v0.13.0

netlify.toml, package.json
Add minify flag to build commands
**Which issue this PR fixes***:
fixes #168 
```release-note
- Make build command minify by default
```
=> Add minify flag to build commands

layouts/partials/js.html
Fix http scripts not loading and loading a dot instead.
```release-note
- contact: Fix recaptcha not working
```
=> Fix http scripts not loading

exampleSite/content/fragments/pricing/code-pricing.md, exampleSite/content/fragments/pricing/pricing/index.md
=> Fix order of fragments in pricing fragment example

layouts/partials/fragments/list.html
Add missing scratch to pagination helper call
```release-note
- list: Fix pagination not displaying pages
```
=> Add missing scratch to pagination helper call

layouts/partials/helpers/publish-date.html
Date format in publish date was wrong, causing dates to be wrong
fixes #377 
```release-note
- list, content: Displayed date is fixed
```
=> Fix date format messing up date

layouts/partials/fragments/contact.html
Fixes Netlify form submission issues
fixes #43 
```release-note
- contact: Fix contact form not submitting data in Netlify
```
=> Fix netlify form support

assets/styles/index.scss, exampleSite/config.toml
fixes #402
```release-note
- BREAKING: Change color configuration to only configure theme colors
```
=> Change global colors configuration

layouts/partials/fragments/faq.html
Adds section header helper to FAQ fagment
fixes #411
=> Add faq section header helper

exampleSite/content/fragments/config/code-config.md, exampleSite/content/fragments/config/config.md, exampleSite/content/fragments/config/index.md, layouts/partials/fragments/config.html, layouts/partials/head.html, layouts/partials/helpers/config.html, layouts/partials/helpers/fragments.html, layouts/partials/js.html
Adds new config fragment and it's showcase/documentation page
fixes #132 
```release-note
- config: New config fragment
```
=> Create new config fragment

layouts/404.html, layouts/partials/fragments/list.html, layouts/partials/helpers/fragments.html
Migrate 404 page to work like base layout and fix list fragment to work within 404 page
fixes #423, #437
```release-note
- 404: Add missing support for slots
```
=> Fix 404 layout issues

layouts/partials/fragments/faq.html
Cannot open/close questions
fixes #389
```release-note
- faq: Change id of each answer 
```
=> Fix two faq fragements

exampleSite/content/_global/nav.md, exampleSite/content/fragments/nav/code-nav-example.md, exampleSite/content/fragments/nav/docs.md, exampleSite/content/fragments/nav/nav-example.md, layouts/partials/fragments/nav.html
Make navbar sticky through the use of `sticky` variable
fixes #473
-->
```release-note
- nav: Navbar now has `sticky` variable
```
=> Add sticky variable to nav fragment

exampleSite/content/fragments/copyright/docs.md, exampleSite/content/fragments/footer/docs.md, exampleSite/content/fragments/nav/docs.md, layouts/partials/head.html
- Patch `.Site.Params.custom.favicon*` not working
- Document "one instance" fragments
fixes #495 
fixes #490 
```release-note
- Configuration: Fix favicons not working properly
```
=> Patch and document some issues

exampleSite/content/fragments/hero/code-hero.md, exampleSite/content/fragments/hero/docs.md, exampleSite/content/fragments/hero/hero/index.md, layouts/partials/fragments/hero.html
Add title_page variable to hero fragment
```release-note
- hero: Add title_page variable to hero fragment
```
=> Add title_page variable to hero fragment

assets/styles/index.scss, exampleSite/config.toml, exampleSite/content/docs/development/content.md
- Add fontawesome pro support
- Document fontawesome behavior
fixes #526 
```release-note
- Fontawesome: Add Pro support
- Documentation: Add documentation for FontAwesome
```
=> Add fontawesome pro support and document fontawesome behavior

assets/js/contact.js
Fixes #511
PoC patch. Happy if you want to iterate on this.
=> Enable preventDefault by making event cancelable

netlify.toml, theme.toml
=> Fix netlify

layouts/partials/fragments/contact.html
=> Fix contact form readability issues in the success state

layouts/partials/fragments/contact.html, layouts/partials/fragments/list.html, layouts/partials/fragments/nav.html, layouts/partials/fragments/toc.html, layouts/partials/head.html, layouts/partials/helpers/fragments.html
Fix v0.55.5 deprecation warnings
fixes #566
=> Fix deprecation warnings

i18n/pt.yaml
Portuguese translation. I've just updated by comparing to the original English en.yaml
=> Portuguese translation

i18n/fr.yaml
**What this PR does / why we need it:**
French translation based on the english file.
=> French translation

exampleSite/config-dev.toml, exampleSite/config.toml
Fixes: #578
```release-note
```
=> Fix GoogleAnalytics order in config

.github/workflows/cypress.yml
=> Add cypress github actions workflow

exampleSite/content/docs/installation/content.md, layouts/partials/head.html
Update some 0.15 version number left
=> Update version to v0.16 leftovers

exampleSite/content/fragments/portfolio/code-portfolio.md
fix formatting for subitem code in docs
```release-note
```
=> fix formatting for subitem code

CHANGELOG.md
=> Fix release links

exampleSite/content/docs/installation/content.md
=> Switch installation instructions to v0.16.2

exampleSite/content/fragments/list/code-list-tiled.md, exampleSite/content/fragments/list/code-list.md, exampleSite/content/fragments/list/list-tiled.md, exampleSite/content/fragments/list/list.md
=> Fix section path

i18n/nl.yaml
Add a nl.yaml for the Dutch translation.
```release-note
```
=> Create Dutch translation

exampleSite/content/docs/fragments/content.md
fixes #743
```release-note
- Update documentation
```
=> Add documentation on how to disable a global fragment

i18n/en.yaml, i18n/es.yaml
Add Spanish translation and one missing item
```release-note
Added Spanish translation
```
=> Spanish translation

exampleSite/content/docs/supported-colors/content.md
Update supported colors documentation with better explanation.
fixes #750
=> Update supported colors documentation with better explanation

layouts/partials/fragments/list.html
=> fix issue 831 : read more link on list page stays on the same page
